version: '3'

services:
  proxy:
    image: docker.pkg.github.com/williamjacksn/docker-caddy-lego/caddy-lego
    ports: 
      - 8080:80
      - 8443:443
    depends_on:
      - commento
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - caddy_data:/data
    restart: unless-stopped

  commento:
    image: registry.gitlab.com/commento/commento:v1.8.0
    environment:
      COMMENTO_ORIGIN: http://localhost:8081
      COMMENTO_PORT: 8081
      COMMENTO_POSTGRES: postgres://postgres:postgres@db:5432/commento?sslmode=disable
    depends_on:
      - db
    networks:
      - db_network
    restart: unless-stopped
  
  db:
    image: postgres
    environment:
      POSTGRES_DB: commento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - db_network
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  db_network:

volumes:
  postgres_data_volume:
  caddy_data:
