version: '3'

services:
  proxy:
    image: docker.pkg.github.com/williamjacksn/docker-caddy-lego/caddy-lego:2.0.0
    ports: 
      - 80:80
      - 443:443
    environment:
      DUCKDNS_TOKEN:
    depends_on:
      - commento
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddydat:/data
    networks:
      - db_network
    restart: unless-stopped

  commento:
    image: registry.gitlab.com/commento/commento:v1.8.0
    env_file:
      - $PWD/commento.env
    depends_on:
      - db
    networks:
      - db_network
    restart: unless-stopped
  
  db:
    image: postgres
    environment:
      POSTGRES_DB: commento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - db_network
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  db_network:

volumes:
  postgres_data_volume:
  caddydat:
